server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.shardingdemo.entity
#showSql
logging:
  level:
    com:
      example:
        mapper : debug


spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
        username: nacos
        password: nacos123
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/springboot2?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
        username: nacos
        password: nacos123
    sharding:
      tables:
        user:
          actual-data-nodes: ds0.user_$->{[0,2]},ds1.user_$->{[1,3]}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: user_$->{id % 4}
          key-generator:
            column: id
            type: SNOWFLAKE
          database-strategy:
            inline:
              sharding-column: id
              algorithm-expression: ds$->{id % 2}
        user_d:
          actual-data-nodes: ds0.user_d_$->{[0,1,2,3]}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: user_d_$->{id % 4}
          key-generator:
            column: id
            type: SNOWFLAKE
          database-strategy:
            inline:
              sharding-column: id
              algorithm-expression: ds0
        user_c:
          actual-data-nodes: ds0.user_c_$->{[0,2]},ds1.user_c_$->{[1,3]}
          table-strategy:
            standard:
              sharding-column: id
              precise-algorithm-class-name: com.example.shardingdemo.config.UserShardingAlgorithm
          key-generator:
            column: id
            type: SNOWFLAKE
          database-strategy:
            standard:
              sharding-column: id
              precise-algorithm-class-name: com.example.shardingdemo.config.UserAlgorithm
      default-data-source-name: ds0
agehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
